---
version: '3.2'

services:
  master:
    image: hss/jenkins-master:latest
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
    secrets:
      - jenkins-user
      - jenkins-pass

volumes:
  jenkins-data:

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
