version: '3.2'
services:
  jenkins-master:
    build: .
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
volumes:
  jenkins-data:
