---
version: '3.3'

services:
  master:
    image:
      ${AWS_ACCOUNT}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/hss/jenkins-master:latest
    environment:
      JAVA_OPTS:
        "-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false -Djenkins.CLI.disabled=true"
      JENKINS_USER: ${JENKINS_USER}
      JENKINS_PASS: ${JENKINS_PASS}
      GITHUB_USER: ${GITHUB_USER}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
